package de.bw.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-13T20:03:56.168+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://webservices.bw.de/", name = "Buchverwaltung")
@XmlSeeAlso({ObjectFactory.class})
public interface Buchverwaltung {

    @RequestWrapper(localName = "neuesBuchHinzufuegen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.NeuesBuchHinzufuegen")
    @WebMethod
    @ResponseWrapper(localName = "neuesBuchHinzufuegenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.NeuesBuchHinzufuegenResponse")
    public void neuesBuchHinzufuegen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    ) throws BuecherweltException_Exception;

    @RequestWrapper(localName = "anzahlVerringern", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.AnzahlVerringern")
    @WebMethod
    @ResponseWrapper(localName = "anzahlVerringernResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.AnzahlVerringernResponse")
    public void anzahlVerringern(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws BuecherweltException_Exception;

    @RequestWrapper(localName = "buchBearbeiten", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.BuchBearbeiten")
    @WebMethod
    @ResponseWrapper(localName = "buchBearbeitenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.BuchBearbeitenResponse")
    public void buchBearbeiten(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    ) throws BuecherweltException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBuchMitIdEins", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetBuchMitIdEins")
    @WebMethod
    @ResponseWrapper(localName = "getBuchMitIdEinsResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetBuchMitIdEinsResponse")
    public de.bw.webservices.Buch getBuchMitIdEins();

    @RequestWrapper(localName = "buchLoeschen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.BuchLoeschen")
    @WebMethod
    @ResponseWrapper(localName = "buchLoeschenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.BuchLoeschenResponse")
    public void buchLoeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buchSuchen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.BuchSuchen")
    @WebMethod
    @ResponseWrapper(localName = "buchSuchenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.BuchSuchenResponse")
    public de.bw.webservices.Buch buchSuchen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllBuecher", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetAllBuecher")
    @WebMethod
    @ResponseWrapper(localName = "getAllBuecherResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetAllBuecherResponse")
    public java.util.List<de.bw.webservices.Buch> getAllBuecher();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LoginResponse")
    public de.bw.webservices.UserLoginResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @RequestWrapper(localName = "anzahlErhoehen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.AnzahlErhoehen")
    @WebMethod
    @ResponseWrapper(localName = "anzahlErhoehenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.AnzahlErhoehenResponse")
    public void anzahlErhoehen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws BuecherweltException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LogoutResponse")
    public de.bw.webservices.ReturncodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
