
package de.bw.webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-23T22:54:30.919+02:00
 * Generated source version: 2.7.13
 */

@WebFault(name = "InvalidLoginException", targetNamespace = "http://webservices.bw.de/")
public class InvalidLoginException_Exception extends Exception {
    
    private de.bw.webservices.InvalidLoginException invalidLoginException;

    public InvalidLoginException_Exception() {
        super();
    }
    
    public InvalidLoginException_Exception(String message) {
        super(message);
    }
    
    public InvalidLoginException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidLoginException_Exception(String message, de.bw.webservices.InvalidLoginException invalidLoginException) {
        super(message);
        this.invalidLoginException = invalidLoginException;
    }

    public InvalidLoginException_Exception(String message, de.bw.webservices.InvalidLoginException invalidLoginException, Throwable cause) {
        super(message, cause);
        this.invalidLoginException = invalidLoginException;
    }

    public de.bw.webservices.InvalidLoginException getFaultInfo() {
        return this.invalidLoginException;
    }
}
