package de.bw.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-16T19:06:57.859+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://webservices.bw.de/", name = "Kundenverwaltung")
@XmlSeeAlso({ObjectFactory.class})
public interface Kundenverwaltung {

    @RequestWrapper(localName = "kundeLoeschen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeLoeschen")
    @WebMethod
    @ResponseWrapper(localName = "kundeLoeschenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeLoeschenResponse")
    public void kundeLoeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loginKunde", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LoginKunde")
    @WebMethod
    @ResponseWrapper(localName = "loginKundeResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LoginKundeResponse")
    public boolean loginKunde(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "kundeSuchen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeSuchen")
    @WebMethod
    @ResponseWrapper(localName = "kundeSuchenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeSuchenResponse")
    public de.bw.webservices.Kunde kundeSuchen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "kundeHinzufuegen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeHinzufuegen")
    @WebMethod
    @ResponseWrapper(localName = "kundeHinzufuegenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeHinzufuegenResponse")
    public de.bw.webservices.Kunde kundeHinzufuegen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9
    ) throws BuecherweltException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllKunden", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetAllKunden")
    @WebMethod
    @ResponseWrapper(localName = "getAllKundenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetAllKundenResponse")
    public java.util.List<de.bw.webservices.Kunde> getAllKunden();

    @RequestWrapper(localName = "kundeBearbeiten", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeBearbeiten")
    @WebMethod
    @ResponseWrapper(localName = "kundeBearbeitenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.KundeBearbeitenResponse")
    public void kundeBearbeiten(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9
    );

    @RequestWrapper(localName = "logout", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LogoutResponse")
    public void logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
