package de.bw.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-16T19:07:12.832+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://webservices.bw.de/", name = "Mitarbeiterverwaltung")
@XmlSeeAlso({ObjectFactory.class})
public interface Mitarbeiterverwaltung {

    @RequestWrapper(localName = "mitarbeiterLoeschen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.MitarbeiterLoeschen")
    @WebMethod
    @ResponseWrapper(localName = "mitarbeiterLoeschenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.MitarbeiterLoeschenResponse")
    public void mitarbeiterLoeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllMitarbeiter", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetAllMitarbeiter")
    @WebMethod
    @ResponseWrapper(localName = "getAllMitarbeiterResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.GetAllMitarbeiterResponse")
    public java.util.List<de.bw.webservices.Mitarbeiter> getAllMitarbeiter();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loginMitarbeiter", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LoginMitarbeiter")
    @WebMethod
    @ResponseWrapper(localName = "loginMitarbeiterResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LoginMitarbeiterResponse")
    public boolean loginMitarbeiter(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "mitarbeiterBearbeiten", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.MitarbeiterBearbeiten")
    @WebMethod
    @ResponseWrapper(localName = "mitarbeiterBearbeitenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.MitarbeiterBearbeitenResponse")
    public void mitarbeiterBearbeiten(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9
    );

    @RequestWrapper(localName = "neuenMitarbeiterHinzufuegen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.NeuenMitarbeiterHinzufuegen")
    @WebMethod
    @ResponseWrapper(localName = "neuenMitarbeiterHinzufuegenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.NeuenMitarbeiterHinzufuegenResponse")
    public void neuenMitarbeiterHinzufuegen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9
    ) throws BuecherweltException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LoginResponse")
    public de.bw.webservices.UserLoginResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "mitarbeiterSuchen", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.MitarbeiterSuchen")
    @WebMethod
    @ResponseWrapper(localName = "mitarbeiterSuchenResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.MitarbeiterSuchenResponse")
    public de.bw.webservices.Mitarbeiter mitarbeiterSuchen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://webservices.bw.de/", className = "de.bw.webservices.LogoutResponse")
    public de.bw.webservices.ReturncodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
